import { forwardRef, useRef, useState } from "react";
import { getThumbUrl, getThumbUrlWebp, isFirebaseStorageUrl } from "@utils/mediaUtils";

interface ThumbImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  /** Original full-resolution URL (Firebase Storage, Cloudinary, local asset, etc.) */
  src: string;
  /** Size suffix matching the Resize Images extension config, e.g. "400x400" */
  thumbSize?: string;
  alt?: string;
}

/**
 * Drop-in <img> replacement for gallery thumbnails.
 *
 * - Firebase Storage URLs: replaced with the thumbnail path generated by the
 *   "Resize Images" extension (thumbnails/ subfolder, same token).
 * - Tries the original extension first (e.g. _400x400.jpg). If the image fails
 *   to load (404), falls back to the .webp variant (_400x400.webp) once.
 * - All other URLs (local assets, Cloudinary, etc.): passed through unchanged.
 * - Always sets loading="lazy" for deferred loading.
 * - Forwards ref so parent components can read naturalWidth for cache detection.
 */
const ThumbImage = forwardRef<HTMLImageElement, ThumbImageProps>(
  ({ src, thumbSize = "400x400", alt = "", onError, loading = "lazy", ...props }, ref) => {
    const [fallbackSrc, setFallbackSrc] = useState<string | null>(null);
    const fallbackTried = useRef(false);

    const isFirebase = isFirebaseStorageUrl(src);
    const isGif = typeof src === 'string' && src.split("?")[0].toLowerCase().endsWith(".gif");

    const displaySrc = isFirebase
      ? (fallbackSrc ?? (isGif ? src : getThumbUrl(src, thumbSize)))
      : src;

    const handleError = (e: React.SyntheticEvent<HTMLImageElement>) => {
      if (isFirebase) {
        if (!fallbackTried.current) {
          fallbackTried.current = true;
          setFallbackSrc(getThumbUrlWebp(src, thumbSize));
        } else if (fallbackSrc !== src) {
          setFallbackSrc(src);
        }
      }
      onError?.(e);
    };

    
    return (
      <picture style={{ display: "contents" }}>
        {isFirebase && !fallbackTried.current && !isGif && (
          <source srcSet={getThumbUrlWebp(src, thumbSize)} type="image/webp" />
        )}
        {/* eslint-disable-next-line jsx-a11y/alt-text */}
        <img
          ref={ref}
          src={displaySrc}
          alt={alt}
          loading={loading}
          onError={handleError}
          {...props}
        />
      </picture>
    );
  }
);

ThumbImage.displayName = "ThumbImage";

export default ThumbImage;
